#自定义写死用户测试数据
# 在末尾添加了一个新的用户数据
sp:
  user-service:
    users: "[{\"id\":7, \"username\":\"abc\",\"password\":\"123\"},{\"id\":8, \"username\":\"def\",\"password\":\"456\"},{\"id\":9, \"username\":\"ghi\",\"password\":\"789\"},{\"id\":99, \"username\":\"aaa\",\"password\":\"111\"},{\"id\":100,\"isername\":yangsonglin,\"password\":\"960720\"}]"
spring:
  application:
    name: user-service
  rabbitmq:
    host: 192.168.72.133
    port: 5672
    username: admin
    password: admin
        
server:
  port: 8101

#eureka的注册路径  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka